sudo: required

install:
  - sudo apt-get install ruby-dev
  # Must have at least Ruby 1.9.3 (2.0.0 recommended) for travis CLI
  - ruby -v
  # Use https://github.com/travis-ci/travis.rb
  - sudo gem install travis -v 1.8.8 --no-rdoc --no-ri
  - travis version

script: 
  - travis status --repo richelbilderbeek/correct_cpp